- name: Make sure apticron is installed
  apt:
      pkg:
        - apticron
        - unattended-upgrades
      state: present

- name: Copy unattended-upgrades configuration
  copy:
    src: apt/
    dest: /etc/apt/apt.conf.d/
    owner: root
    group: root
    mode: 0644
