- name: update apt cache
  apt: update_cache=yes

- name: Install required system and dev packages.
  apt:
      pkg:
         - build-essential
         - mailutils
         - aptitude
      state: present

