---
- name: Install basic list of packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - 'apt-transport-https'
      - 'ca-certificates'
      - 'curl'
      - 'gnupg2'
      - 'software-properties-common'

- name: Set up apt proxy host
  template:
    src: apt_00proxy.j2
    dest: /etc/apt/apt.conf.d/00proxy
    mode: 0644
  when: (apt_proxy_host is defined)


