---
- name: GITLAB-CONFIG | Create gitlab.rb fragments directory
  file:
    path: /etc/gitlab/conf.d
    state: directory
    mode: 0700

# configurations
- { include: config_app.yml, when: (gitlab_standalone|bool or 'gitlab_app' in group_names) }

- name: GITLAB-CONFIG | Assemble! gitlab.rb
  assemble:
    src: /etc/gitlab/conf.d/
    dest: /etc/gitlab/gitlab.rb
  notify:
    - reconfigure gitlab

- name: GITLAB-CONFIG  | Reconfigure GitLab now (first run).
  command:
    cmd: gitlab-ctl reconfigure
    creates: /var/opt/gitlab/bootstrapped
  failed_when: false


