---
k3d_arch: k3d-linux-amd64
k3d_version: v5.0.1
k3d_checksum: 84a45821b16df2fb60ab9144bad3d0e67805a2bfee17bee51b09bc1e75c0fc10
gcp_mtu: 1460
docker_network_mtu: "{{ gcp_mtu }}"
tcp_mss_mtu: "{{ docker_network_mtu|int - 90}}"
alternate_ssh_port: 24
use_alternate_ssh_port: false
