---
k3d_arch: k3d-linux-amd64
k3d_version: v5.2.0
k3d_checksum: 223bcbf2a6c407e72910727d47dcaae5d4ed1c90d356d9bee968b385d645e806
gcp_mtu: 1460
docker_network_mtu: "{{ gcp_mtu }}"
tcp_mss_mtu: "{{ docker_network_mtu|int - 90}}"
alternate_ssh_port: 24
use_alternate_ssh_port: false
