---
k3d_arch: k3d-linux-amd64
k3d_version: v4.4.7
k3d_checksum: 51731ffb2938c32c86b2de817c7fbec8a8b05a55f2e4ab229ba094f5740a0f60
gcp_mtu: 1460
docker_network_mtu: "{{ gcp_mtu }}"
tcp_mss_mtu: "{{ docker_network_mtu|int - 90}}"
alternate_ssh_port: 24
use_alternate_ssh_port: false
