---
k3d_arch: k3d-linux-amd64
k3d_version: v3.4.0
k3d_checksum: 1c961f1161d7b7fb55658ee32081b250a0da6d5f81e40c307a0300e3e130d19f
gcp_mtu: 1460
docker_network_mtu: "{{ gcp_mtu }}"
tcp_mss_mtu: "{{ docker_network_mtu|int - 90}}"
alternate_ssh_port: 24
use_alternate_ssh_port: false
