---
k3d_arch: k3d-linux-amd64
k3d_version: v4.4.8
k3d_checksum: 7a89e3693fa17fae4e8cefdeb4c65db49c377f78328d708d0bfd304b89719625
gcp_mtu: 1460
docker_network_mtu: "{{ gcp_mtu }}"
tcp_mss_mtu: "{{ docker_network_mtu|int - 90}}"
alternate_ssh_port: 24
use_alternate_ssh_port: false
