---
k3d_arch: k3d-linux-amd64
k3d_version: v4.2.0
k3d_checksum: 745396701fb0ffaa832b02c5b734fd5b6bb042ac878b3ad16bb810ebbf02df0c
gcp_mtu: 1460
docker_network_mtu: "{{ gcp_mtu }}"
tcp_mss_mtu: "{{ docker_network_mtu|int - 90}}"
alternate_ssh_port: 24
use_alternate_ssh_port: false
