---
k3d_arch: k3d-linux-amd64
k3d_version: v4.4.6
k3d_checksum: 4e45de05370dbe37d9704bf31735b2fe04c77b4f7a1a965265592b583367ba7f
gcp_mtu: 1460
docker_network_mtu: "{{ gcp_mtu }}"
tcp_mss_mtu: "{{ docker_network_mtu|int - 90}}"
alternate_ssh_port: 24
use_alternate_ssh_port: false
