---
k3d_arch: k3d-linux-amd64
k3d_version: v5.4.1
k3d_checksum: 50f64747989dc1fcde5db5cb82f8ac132a174b607ca7dfdb13da2f0e509fda11
gcp_mtu: 1460
docker_network_mtu: "{{ gcp_mtu }}"
tcp_mss_mtu: "{{ docker_network_mtu|int - 90}}"
alternate_ssh_port: 24
use_alternate_ssh_port: false
