---
k3d_arch: k3d-linux-amd64
k3d_version: v5.0.3
k3d_checksum: '018421fdff567df5df3840e75501a40199501ce6bf25e1f2dd259f74e13519f3'
gcp_mtu: 1460
docker_network_mtu: "{{ gcp_mtu }}"
tcp_mss_mtu: "{{ docker_network_mtu|int - 90}}"
alternate_ssh_port: 24
use_alternate_ssh_port: false
