---
k3d_arch: k3d-linux-amd64
k3d_version: v5.2.1
k3d_checksum: 70141637bbe7531d17cf313688520287572e78711361e7162237648a59a6e91d
gcp_mtu: 1460
docker_network_mtu: "{{ gcp_mtu }}"
tcp_mss_mtu: "{{ docker_network_mtu|int - 90}}"
alternate_ssh_port: 24
use_alternate_ssh_port: false
