---
k3d_arch: k3d-linux-amd64
k3d_version: v4.1.0
k3d_checksum: 108edf8bc3a6d4498620b56cdc46137e4426e6349fd64b47e922a94da3186536
gcp_mtu: 1460
docker_network_mtu: "{{ gcp_mtu }}"
tcp_mss_mtu: "{{ docker_network_mtu|int - 90}}"
alternate_ssh_port: 24
use_alternate_ssh_port: false
