---
k3d_arch: k3d-linux-amd64
k3d_version: v4.3.0
k3d_checksum: afb1a4b2df657c3721cc4034a381c05c3c7cc343198103157317d1e891f2ee7f
gcp_mtu: 1460
docker_network_mtu: "{{ gcp_mtu }}"
tcp_mss_mtu: "{{ docker_network_mtu|int - 90}}"
alternate_ssh_port: 24
use_alternate_ssh_port: false
