---
k3d_arch: k3d-linux-amd64
k3d_version: v4.1.1
k3d_checksum: 4148b8035774a2765969898cc73066491ac718d1b2890415a4625931aaacd3ac
gcp_mtu: 1460
docker_network_mtu: "{{ gcp_mtu }}"
tcp_mss_mtu: "{{ docker_network_mtu|int - 90}}"
alternate_ssh_port: 24
use_alternate_ssh_port: false
