---
k3d_arch: k3d-linux-amd64
k3d_version: v4.4.4
k3d_checksum: 6d4ac3d4c5b084f445980e427c5d3a75eefd2c39a22d028825c234c6c20d1e46
gcp_mtu: 1460
docker_network_mtu: "{{ gcp_mtu }}"
tcp_mss_mtu: "{{ docker_network_mtu|int - 90}}"
alternate_ssh_port: 24
use_alternate_ssh_port: false
