- hosts: all
  serial: 1
  remote_user: root
  become: yes
  vars:
    ansible_python_interpreter: '/usr/bin/python3'

  tasks:
    - name: Use an apt proxy host
      import_role:
        name: packageproxy
        tasks_from: client.yml
      when: (apt_proxy_host is defined)

    - name: Install k3s
      include_role:
        name: k3s
      when: (k3s_version is defined)

    - name: Install GitLab Omnibus
      include_role:
        name: omnibus
      when: (gitlab_version is defined)

    - name: Install GitLab Runner
      include_role:
        name: gitlab_runner
      when: (gitlab_runner_version is defined)
