- name: Install ufw
  apt: pkg=ufw state=present

- name: reset ufw
  ufw: state=reset

- name: Allow all access from RFC1918 networks to this host
  ufw:
    rule: allow
    src: '{{ item }}'
  loop:
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16

- name: open SSH port
  ufw: rule=allow name=OpenSSH

- name: copy custom SSH port rule
  copy:
    src: openssh-server-custom
    dest: /etc/ufw/applications.d/openssh-server-custom
    owner: root
    group: root
    mode: 0644

- name: open Custom SSH Port
  ufw: rule=allow name='OpenSSHCustom'
  ignore_errors: True

- name: Allow all access to tcp port 80
  ufw:
    rule: allow
    port: '80'
    proto: tcp
  when: (ufw_allow_web_access is defined) and (ufw_allow_web_access|bool)

- name: Allow all access to tcp port 443
  ufw:
    rule: allow
    port: '443'
    proto: tcp
  when: (ufw_allow_web_access is defined) and (ufw_allow_web_access|bool)


- name: allow defined ip's access to everything
  ufw: rule=allow src={{ item }} insert=1
  with_items: "{{ ufw_always_allow_list }}"
  when: (ufw_always_allow_list is defined) and (ufw_always_allow_list|length > 0)
  ignore_errors: True

- name: block offending ip's when defined
  ufw: rule=deny logging=on src={{ item }} insert=1
  with_items: "{{ ufw_always_block_list }}"
  when: (ufw_always_block_list is defined) and (ufw_always_block_list|length > 0)
  ignore_errors: True

# sigh:  https://github.com/ansible/ansible/issues/45446
- name: Configure the kernel to keep connections alive when enabling the firewall
  sysctl:
    name: net.netfilter.nf_conntrack_tcp_be_liberal
    value: '1'
    state: present
    sysctl_set: yes
    reload: yes

- name: make sure ufw is enabled
  ufw:
    state: enabled
    direction: "{{ item.direction }}"
    policy: "{{ item.policy }}"
  with_items:
    - { direction: 'incoming', policy: 'deny' }
    - { direction: 'outgoing', policy: 'allow' }
