---
- name: OMNIBUS | SETUP | Make sure /etc/gitlab exists
  file:
    path: /etc/gitlab
    state: directory
    mode: 0755

- name: OMNIBUS | SETUP | Skip running reconfigure on install
  file:
    path: /etc/gitlab/skip-auto-reconfigure
    state: touch
    mode: 0755

- name: OMNIBUS | APT | Make sure apt is setup for external repositories
  import_role:
    name: aptprep
    tasks_from: main.yml

- name: OMNIBUS | APT | Add GitLab GPG key
  apt_key:
    url: https://packages.gitlab.com/gpg.key
    id:  F6403F6544A38863DAA0B6E03F01618A51312F3F
    state: present

- name: OMNIBUS | APT | Add GitLab APT repository
  apt_repository:
    repo: deb {{ gitlab_package_host }} {{ansible_distribution_release}} main
    state: present
    update_cache: yes

- name: OMNIBUS | APT | Install Omnibus dependencies
  become: yes
  apt:
    pkg:
      - curl
      - openssh-server
      - ca-certificates
      - postfix
      - python
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: OMNIBUS | APT | Install Omnibus-GitLab
  apt:
    pkg: "{{ gitlab_package }}"

- name: OMNIBUS | SETUP | Move package gitlab.rb out of the way
  copy:
    remote_src: yes
    src: /etc/gitlab/gitlab.rb
    dest: "/etc/gitlab/gitlab.rb.{{ the_time_is_now }}"
  ignore_errors: True


- name: OMNIBUS | SETUP | MAKE SURE TO REMOVE THE SKIP FILE
  file:
    path: /etc/gitlab/skip-auto-reconfigure
    state: absent

