---
- name: GITLAB INITIAL SETUP | Check if already initialized
  stat:
    path: /etc/gitlab/initialized
  register: initialized_file

- { include: initial_rails_settings.yml, when: (not initialized_file.stat.exists and not gitlab_force_initial_setup) }

- name: GITLAB INITIAL SETUP | Set "initialized"
  file:
    path: /etc/gitlab/initialized
    state: touch
    mode: 0755
