---
- name: DBSERVER | BACKUPS | install packages for backups
  apt:
    state: present
    name: "{{ packages }}"
  vars:
    packages:
    - percona-xtrabackup

# backups
- name: DBSERVER | BACKUPS | Copy xtrabackup script
  copy:
    src: autoxtrabackup.sh
    dest: /srv/scripts/autoxtrabackup.sh
    owner: root
    group: root
    mode: 0755

- name: DBSERVER | BACKUPS | Copy autoxtrabackup config
  copy:
    src: autoxtrabackup.config
    dest: /etc/default/autoxtrabackup
    owner: root
    group: root
    mode: 0755

# cron jobs
- name: DBSERVER | BACKUPS | Copy autoxtrabackup cron
  copy:
    src: "autoxtrabackup.cron"
    dest: /etc/cron.d/autoxtrabackup
    owner: root
    group: root
    mode: 0644
