- hosts: all
  become: no
  become_method: sudo
  vars:
    initial_provision_file: "{{ vagrant_setup_path }}/{{ inventory_hostname }}.initialprovision"

  tasks:
    - name: VAGRANT INITIAL PROVISIONING | ping!
      action: ping

    - name: VAGRANT INITIAL PROVISIONING | Create initial provision file
      copy:
        content: "Initial provision: {{ ansible_date_time.iso8601 }}"
        dest: "{{ initial_provision_file }}"
      delegate_to: localhost
