---
- name: INITIAL RAILS SETTINGS | create temporary file
  tempfile:
    state: file
    suffix: .rb
  register: initial_rails_settings_script

- name: INITIAL RAILS SETTINGS | copy initial_rails_settings script
  template:
    src: initial_rails_settings.rb.j2
    dest: "{{ initial_rails_settings_script.path }}"
    owner: git
    group: git
    mode: 0600

- name: INITIAL RAILS SETTINGS |  Run initial_rails_settings script
  command:
    cmd: gitlab-rails runner "{{ initial_rails_settings_script.path }}"

# - name: INITIAL RAILS SETTINGS | Remove the script
#   file:
#     path: "{{ initial_rails_settings_script.path }}"
#     state: absent
#   when: (initial_rails_settings_script.path is defined)
