- name: Make sure postfix is installed
  apt: 
    name: postfix 
    state: present

- name: manage mailname
  template:
    src:  etc_mailname.j2
    dest: /etc/mailname
    owner: root
    group: root
    mode:  0644

- name: manage virtual map
  template:
    src: virtual.j2
    dest: /etc/postfix/virtual
    owner: root
    group: root
    mode:  0644
  notify: 
    - run postmap virtual
    - restart postfix

- name: copy postfix main.cf
  template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode:  0644
  notify: restart postfix

- name: copy aliases
  copy:
    src: etc_aliases
    dest: /etc/aliases
    owner: root
    group: root
    mode: 0644
  notify: run postalias
