---
- name: CLEANUP | Stop the cluster
  shell: "k3d cluster stop {{ k3d_cluster_name }}"
  become: no
  when: (is_cleanup|default(false))

- name: CLEANUP | Delete the cluster
  shell: "k3d cluster delete {{ k3d_cluster_name }}"
  become: no
  when: (is_cleanup|default(false))

- name: CLEANUP | Delete the bridge network for the cluster
  docker_network:
    name: "{{ k3d_cluster_name}}_net"
    state: absent
    force: yes
  when: (is_cleanup|default(false))

- name: CLEANUP | Remove cluster creation script
  file:
    dest: "~/create_{{ k3d_cluster_name }}_cluster.sh"
    state: absent
  become: no
  when: (is_cleanup|default(false))

- name: CLEANUP | Remove bindmount directories
  file:
    state: absent
    path: "/data/k3d/{{ k3d_cluster_name}}/"
  when: (is_cleanup|default(false))
