---
- name: Start Mailhog container
  docker_container:
    name: mailhog
    image: mailhog/mailhog:latest
    state: started
    restart_policy: always
    ports:
     - "1025:1025"
     - "8025:8025"