---
- name: Install basic list of packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - 'apt-transport-https'
      - 'ca-certificates'
      - 'curl'
      - 'gnupg2'
      - 'software-properties-common'