---
- name: GITLAB.RB | application server settings
  template:
    src: gitlab_rb_conf/application.rb.j2
    dest: /etc/gitlab/conf.d/application.rb
    owner: root
    group: root
    mode: 0600

- name: GITLAB.RB | external gitaly settings
  template:
    src: gitlab_rb_conf/external_gitaly.rb.j2
    dest: /etc/gitlab/conf.d/external_gitaly.rb
    owner: root
    group: root
    mode: 0600
  when: (gitlab_external_gitaly|bool)

# TODO
# gitlab_rails['initial_license_file'] = '/etc/gitlab/company.gitlab-license'


