---
- name: Delete k3s if already present
  file:
    path: /usr/local/bin/k3s
    state: absent


- name: Download k3s binary x64 from k3s releases
  get_url:
    url: "https://github.com/rancher/k3s/releases/download/{{ k3s_version }}/k3s"
    dest: /usr/local/bin/k3s
    owner: root
    group: root
    mode: 0755
  when: (k3s_proxy_url is not defined)

- name: Download k3s binary x64 from local proxy
  get_url:
    url: "{{k3s_proxy_url }}/k3s-{{ k3s_version}}"
    dest: /usr/local/bin/k3s
    owner: root
    group: root
    mode: 0755
  when: (k3s_proxy_url is defined)
