---
- name: Set up addition server args
  set_fact:
    local_kubeconfig:  "{{ local_clusters_path }}/kubeconfig-{{ inventory_hostname_short }}"
  when: (k3s_role == 'server')

- name: KUBECONFIG | Copy the kubeconfig locally
  slurp:
    src:  "/etc/rancher/k3s/k3s.yaml"
  register: remote_kubeconfig
  when: (k3s_role == 'server')
  tags:
    - 'kubeconfig'

- name: KUBECONFIG | Copy the kubeconfig locally
  copy:
    content: "{{ remote_kubeconfig['content'] | b64decode }}"
    dest: "{{ local_kubeconfig }}"
  delegate_to: localhost
  become: no
  when: (k3s_role == 'server')
  tags:
    - 'kubeconfig'

- name: KUBECONFIG | Replace the kubeconfig API Server Address
  replace:
    dest: "{{ local_kubeconfig }}"
    regexp: "{{ k3s_kubectl_api_host }}"
    replace: "{{ k3s_server_ip }}"
  delegate_to: localhost
  become: no
  when: (k3s_role == 'server')
  tags:
    - 'kubeconfig'