
---
- name: PGSERVER | CORE | - add repo key
  apt_key: 
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    id: ACCC4CF8 
    state: present

- name: PGSERVER | CORE | apt - add passenger repo
  apt_repository:
    repo: 'deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_lsb.codename }}-pgdg main'  
    state: present 
    update_cache: yes

- name: PGSERVER | CORE | install postgres packages
  apt:
    state: present
    name: "{{ packages }}"
  vars:
    packages:
    - postgresql-11 
    - pgcli

- name: PGSERVER | CORE | ensure postgresql is running
  service:
    name: postgresql
    state: started
