- name: restart postfix
  service: name=postfix state=restarted

- name: run postalias
  shell: postalias hash:/etc/aliases && newaliases

- name: run postmap virtual
  shell: /usr/sbin/postmap /etc/postfix/virtual