---
- name: create the waldorf group
  group:
    name: waldorf
    gid: '4242'
    state: present

- name: create the waldorf user
  user:
    name: waldorf
    comment: "Systems Administration"
    uid: '4242'
    group: waldorf
    home: /home/waldorf
    createhome: yes
    password: '*'
    update_password: always
    shell: /bin/bash
    state: present

- name: fix the waldorf homedirectory permissions
  file:
    path: /home/waldorf
    owner: waldorf
    group: waldorf
    mode: 0755
    state: directory