- blockinfile: 
    dest: /etc/gitlab/gitlab.rb
    regexp: "#gitlab_rails['ldap_enabled'].*$"   
    block: |
      gitlab_rails['ldap_enabled'] = true
      gitlab_rails['ldap_servers'] = YAML.load <<-'EOS' # remember to close this block with 'EOS' below
        main: # 'main' is the GitLab 'provider ID' of this LDAP server
           label: 'LDAP'
           host: '{{ ldap_host }}'
           port: 389
           uid: 'sAMAccountName'
           method: 'plain' # "tls" or "ssl" or "plain"
           bind_dn: '{{ ldap_binddn }}'
           password: '{{ ldap_pass }}'
           active_directory: true
           allow_username_or_email_login: true
           block_auto_created_users: false
           base: 'ldap_base'
           user_filter: ''
           attributes:
             username: ['uid', 'userid', 'sAMAccountName']
             email:    ['mail', 'email', 'userPrincipalName']
             name:       'cn'
             first_name: 'givenName'
             last_name:  'sn'
           group_base: '{{ ldap_group_base }}' 
           admin_group: '{{ ldap_admin_group }}' 
           sync_ssh_keys: false
      EOS
    
