---
- name: Make sure apticron is installed
  apt:
      pkg:
        - apticron
        - unattended-upgrades
      state: present

- name: Copy unattended-upgrades configuration
  template:
    src: '{{ item.src }}'
    dest: /etc/apt/apt.conf.d/{{ item.path | regex_replace('\.j2','') }}
    owner: root
    group: root
    mode: 0644
  with_filetree: templates/apt/
  when: item.state == 'file'