# packageproxy
- name: Set Package Proxy
  import_role:
    name: packageproxy
    tasks_from: client
    
- name: update apt cache
  apt: 
    update_cache: yes

- name: Install required system and dev packages.
  apt:
      pkg:
         - build-essential
         - mailutils
         - aptitude
         - net-tools
      state: present
