- name: Get account list
  getent:
    database: passwd

- name: Add waldorf always allowed account keys (double run allows exclusivity)
  authorized_key:
    user: waldorf
    exclusive: yes
    key: "{{ lookup('file', 'public_keys/' + item) }}"
  loop: '{{waldorf_always_allowed_keys}}'

- name: Add waldorf allowed account keys
  authorized_key:
    user: waldorf
    key: "{{ lookup('file', 'public_keys/' + item,  errors='ignore') }}"
  with_items:
    '{{waldorf_allowed_keys | default([])}}'
  when: (item != '')
