---
gitlab_runner_source: "docker" # options: package or docker
gitlab_runner_executor: "docker"
gitlab_runner_description: "gitlab-runner-{{ gitlab_runner_executor }}"
gitlab_runner_tag_list: ""
gitlab_runner_run_untagged: "true"
gitlab_runner_package: "gitlab-runner={{ gitlab_runner_version }}"
gitlab_runner_package_host: "https://packages.gitlab.com/runner/gitlab-runner/ubuntu/"
gitlab_runner_docker_base: "ubuntu" # options: ubuntu or alpine
gitlab_runner_docker_version: "{{ gitlab_runner_docker_base }}-v{{ gitlab_runner_version }}"
gitlab_runner_docker_image: "ubunutu:latest"
gitlab_runner_docker_container_name: "gitlab-runner"
gitlab_runner_docker_privileged: "true"
gitlab_runner_register_args:
  - "--url \"{{ gitlab_registration_server }}\""
  - "--registration-token \"{{ gitlab_runners_registration_token }}\""
  - "--executor \"{{ gitlab_runner_executor }}\""
  - "--locked \"false\""
  - "--access-level \"not_protected\""
  - "--description \"{{ gitlab_runner_description }}\""
  - "--tag-list \"{{ gitlab_runner_tag_list}}\""
  - "--run-untagged \"{{ gitlab_runner_run_untagged}}\""
gitlab_runner_register_docker_args:
  - "--docker-image \"{{ gitlab_runner_docker_image }}\""
  - "--docker-privileged \"{{ gitlab_runner_docker_privileged }}\""
